pipeline:
  name: azure-devops-auth-test
  identifier: azure_devops_auth_test
  projectIdentifier: HarnessCI
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: account.github
        repoName: SudheerNunna123/harness-ci-azure-test
        build:
          type: branch
          spec:
            branch: main

  stages:
    - stage:
        name: Test Azure PAT
        identifier: TestAzurePAT
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: Cloud
            spec:
              platform:
                os: Linux
                arch: Amd64
          execution:
            steps:
              - step:
                  name: Print Hello and Test Azure Auth
                  identifier: HelloAzure
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "✅ Hello from Harness CI!"
                      echo "🔐 Testing Azure DevOps PAT token..."
                      curl -u "your_azure_username:<+secrets.getValue(\"AZURE_DEVOPS_PAT\")>" https://dev.azure.com/your_org/_apis/projects?api-version=6.0
